# Generated by Django 6.0.7 on 2026-07-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
