# Generated by Django 6.0.7 on 2026-07-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='quantity',
        ),
    ]
