# Generated by Django 6.0.7 on 2026-08-02 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_remove_stockproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
